openapi: '3.0.3'
info:
  title: B2B Usage-Based Billing Platform API
  version: '1.0.0'

tags:
  - name: Auth
  - name: Organization
  - name: Customer
  - name: Billing
  - name: Event

paths:
  /v1/auth/register:
    post:
      summary: Create a new account and send email verification
      operationId: register
      tags: [Auth]
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '202':
          description: Registration accepted. Verification email has been sent
          content:
            'application/json':
              schema:
                type: object
        '400':
          description: | 
            Bad request 
            
            Additional codes:
            - 2001: Required name
            - 2002: Required email
            - 2003: Required password
            - 2004: Invalid name
            - 2005: Invalid email
            - 2006: Invalid password
            - 2007: Email is already in use
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: Internal error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  
  /v1/auth/email/verify:
    post:
      summary: Verify email
      operationId: verifyEmail
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailRequest'
      responses:
        '204':
          description: Email verified
        '400':
          description: | 
            Bad request 
            
            Additional codes:
            - 2001: Required token
            - 2002: Invalid token
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: Internal error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/InternalErrorResponse'
  
  /v1/auth/email/resend-verification:
    post:
      summary: Resend email verification
      operationId: resendEmailVerification
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendEmailVerificationRequest'
      responses:
        '204':
          description: Email verification has been resent

  /v1/auth/login:
    post:
      summary: Create a new session
      operationId: login
      tags: [Auth]
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Session created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /v1/auth/refresh:
    post:
      summary: Refresh an access token of session
      operationId: refreshSession
      tags: [Auth]
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/RefreshSessionRequest'
      responses:
        '200':
          description: Session refreshed
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /v1/auth/sessions:
    get:
      summary: Get sessions
      tags: [Auth]
      security: [Bearer: []]
      responses:
        '200':
          description: Session list

    delete:
      summary: Finish all sessions
      operationId: logout
      tags: [Auth]
      security: [Bearer: []]
      responses:
        '204':
          description: Sessions finished

  /v1/auth/sessions/{sessionId}:
    delete:
      summary: Finish the session
      operationId: logout
      tags: [Auth]
      security: [Bearer: []]
      responses:
        '204':
          description: Session finished

  /v1/auth/password/forgot:
    post:
      summary: Send email with reset password link
      tags: [Auth]
      responses:
        '200':
          description: OK

  /v1/auth/password/reset:
    post:
      summary: Reset the password
      tags: [Auth]
      responses:
        '200':
          description: OK

  /v1/auth/password/change:
    post:
      summary: Change the password of authorized user
      tags: [Auth]
      security: [Bearer: []]
      responses:
        '200':
          description: OK

  /v1/auth/switch-organization:
    post:
      summary: Switch an organization in session
      operationId: switchOrganization
      tags: [Auth]
      security: [Bearer: []]
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/SwitchOrganizationRequest'
      responses:
        '200':
          description: Session recreated with selected organization
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SwitchOrganizationResponse'

  /v1/me:
    get:
      summary: Get user info of current session
      operationId: getMe
      tags: [Auth]
      security: [Bearer: []]
      responses:
        '200':
          description: User info returned
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/MeResponse'

  /v1/organizations:
    get:
      summary: Get organizations
      operationId: getOrganizations
      tags: [Organization]
      security: [Bearer: []]
      parameters:
        - name: fromId
          in: query
          description: last id of previous organization list
          schema:
            type: string
      responses:
        '200':
          description: Organization list

    post:
      summary: Create a new organization
      operationId: createOrganization
      tags: [Organization]
      security: [Bearer: []]
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateOrganizationRequest'
      responses:
        '201':
          description: Organization created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/CreateOrganizationResponse'
  
  /v1/organizations/{organizationId}:
    put:
      summary: Update the organization
      tags: [Organization]
      responses:
        '200':
          description: Organization updated
    
    delete:
      summary: Delete the organization
      tags: [Organization]
      responses:
        '200':
          description: Organization deleted

  /v1/organizations/{organizationId}/members:
    get:
      summary: Get organization members
      tags: [Organization]
      responses:
        '200':
          description: Organization member list

  /v1/organizations/{organizationId}/members/{memberId}:
    patch:
      summary: Update organization member
      tags: [Organization]
      responses:
        '200':
          description: Organization member updated

    delete:
      summary: Delete organization member
      tags: [Organization]
      responses:
        '200':
          description: Organization member deleted

  /v1/organizations/{organizationId}/tariffs:
    get:
      summary: Get tariffs
      tags: [Organization]
      responses:
        '200':
          description: Tariff list
    
    post:
      summary: Create a new tariff
      tags: [Organization]
      responses:
        '201':
          description: Tariff created
  
  /v1/organizations/{organizationId}/tariffs/{tariffId}:
    put:
      summary: Update the tariff
      tags: [Organization]
      responses:
        '200':
          description: Tariff updated

    delete:
      summary: Delete the tariff
      tags: [Organization]
      responses:
        '200':
          description: Tariff deleted

  /v1/customers:
    post:
      summary: Create a new customer
      tags: [Customer]
      responses:
        '201':
          description: Tariff created

  /v1/customers/{customerId}/subscribe:
    post:
      summary: Subscribe customer to tariff
      tags: [Customer]
      responses:
        '200':
          description: Customer subscribed
  
  /v1/customer/{customerId}/usage:
    post:
      summary: Add new usage
      tags: [Customer]
      responses:
        '200':
          description: Usage added
  
  /v1/billing/payments:
    get:
      summary: Get payment status
      tags: [Billing]
      responses:
        '200':
          description: Payment status

    post:
      summary: Generate a new payment link
      tags: [Billing]
      responses:
        '200':
          description: Payment link generated
  
  /v1/webhook:
    get:
      summary: Connect to webhook to receive events
      tags: [Event]
      responses:
        '100':
          description: Connected

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    BadRequestResponse:
      type: object
      properties:
        message:
          type: string
          example: Invalid request format
        code:
          type: integer
          example: 1001

    InternalErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: Internal error

    RegisterRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          description: |
            Rules:
            - required field
            - length between 3 and 100
            - first character is letter
        email:
          type: string
          format: email
          description: |
            Rules:
            - required field
            - length no more than 100
            - email format
        password:
          type: string
          format: password
          description: |
            Rules:
            - required field
            - length between 8 and 64
            - at least one letter
            - at least one number

    VerifyEmailRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          format: uuid

    ResendEmailVerificationRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    RefreshSessionRequest:
      type: object
      required:
        - token
      properties:
        token:
          type: string

    AuthResponse:
      type: object
      required:
        - access_token
        - refresh_token
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    SwitchOrganizationRequest:
      type: object
      required:
        - organization_id
      properties:
        organization_id:
          type: string
          format: uuid

    SwitchOrganizationResponse:
      type: object
      required:
        - access_token
      properties:
        access_token:
          type: string

    MeResponse:
      type: object
      properties:
        session_id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        selected_organization:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string

    CreateOrganizationRequest:
      type: object
      properties:
        name:
          type: string

    CreateOrganizationResponse:
      type: object
      required:
        - organization_id
        - access_token
      properties:
        organization_id:
          type: string
          format: uuid
        access_token:
          type: string
