// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=usecase_mock_test.go -package=get_me
//

// Package get_me is a generated GoMock package.
package get_me

import (
	context "context"
	reflect "reflect"

	orgn "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/orgn"
	user "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockuserRepository) Find(ctx context.Context, id string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockuserRepositoryMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockuserRepository)(nil).Find), ctx, id)
}

// MockorgnRepository is a mock of orgnRepository interface.
type MockorgnRepository struct {
	ctrl     *gomock.Controller
	recorder *MockorgnRepositoryMockRecorder
	isgomock struct{}
}

// MockorgnRepositoryMockRecorder is the mock recorder for MockorgnRepository.
type MockorgnRepositoryMockRecorder struct {
	mock *MockorgnRepository
}

// NewMockorgnRepository creates a new mock instance.
func NewMockorgnRepository(ctrl *gomock.Controller) *MockorgnRepository {
	mock := &MockorgnRepository{ctrl: ctrl}
	mock.recorder = &MockorgnRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorgnRepository) EXPECT() *MockorgnRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockorgnRepository) Find(ctx context.Context, id string) (*orgn.Orgn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*orgn.Orgn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockorgnRepositoryMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockorgnRepository)(nil).Find), ctx, id)
}
