// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/verify_email/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/verify_email/usecase.go -destination=internal/app/usecases/verify_email/usecase_mock_test.go -package=verify_email
//

// Package verify_email is a generated GoMock package.
package verify_email

import (
	context "context"
	reflect "reflect"

	user "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/user"
	gomock "go.uber.org/mock/gomock"
)

// MockemailVerificationsRepository is a mock of emailVerificationsRepository interface.
type MockemailVerificationsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockemailVerificationsRepositoryMockRecorder
	isgomock struct{}
}

// MockemailVerificationsRepositoryMockRecorder is the mock recorder for MockemailVerificationsRepository.
type MockemailVerificationsRepositoryMockRecorder struct {
	mock *MockemailVerificationsRepository
}

// NewMockemailVerificationsRepository creates a new mock instance.
func NewMockemailVerificationsRepository(ctrl *gomock.Controller) *MockemailVerificationsRepository {
	mock := &MockemailVerificationsRepository{ctrl: ctrl}
	mock.recorder = &MockemailVerificationsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemailVerificationsRepository) EXPECT() *MockemailVerificationsRepositoryMockRecorder {
	return m.recorder
}

// DeleteTokensByUserID mocks base method.
func (m *MockemailVerificationsRepository) DeleteTokensByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokensByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokensByUserID indicates an expected call of DeleteTokensByUserID.
func (mr *MockemailVerificationsRepositoryMockRecorder) DeleteTokensByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokensByUserID", reflect.TypeOf((*MockemailVerificationsRepository)(nil).DeleteTokensByUserID), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockemailVerificationsRepository) GetByToken(ctx context.Context, token string) (*user.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*user.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockemailVerificationsRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockemailVerificationsRepository)(nil).GetByToken), ctx, token)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// MarkAsVerified mocks base method.
func (m *MockuserRepository) MarkAsVerified(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsVerified", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsVerified indicates an expected call of MarkAsVerified.
func (mr *MockuserRepositoryMockRecorder) MarkAsVerified(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsVerified", reflect.TypeOf((*MockuserRepository)(nil).MarkAsVerified), ctx, userID)
}
