// Code generated by MockGen. DO NOT EDIT.
// Source: endpoint.go
//
// Generated by this command:
//
//	mockgen -source=endpoint.go -destination=endpoint_mock_test.go -package=refresh_session
//

// Package refresh_session is a generated GoMock package.
package refresh_session

import (
	context "context"
	http "net/http"
	reflect "reflect"

	dto "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/usecases/login/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockhttpRouter is a mock of httpRouter interface.
type MockhttpRouter struct {
	ctrl     *gomock.Controller
	recorder *MockhttpRouterMockRecorder
	isgomock struct{}
}

// MockhttpRouterMockRecorder is the mock recorder for MockhttpRouter.
type MockhttpRouterMockRecorder struct {
	mock *MockhttpRouter
}

// NewMockhttpRouter creates a new mock instance.
func NewMockhttpRouter(ctrl *gomock.Controller) *MockhttpRouter {
	mock := &MockhttpRouter{ctrl: ctrl}
	mock.recorder = &MockhttpRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpRouter) EXPECT() *MockhttpRouterMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockhttpRouter) Handle(pattern string, handler http.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", pattern, handler)
}

// Handle indicates an expected call of Handle.
func (mr *MockhttpRouterMockRecorder) Handle(pattern, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockhttpRouter)(nil).Handle), pattern, handler)
}

// Mockusecase is a mock of usecase interface.
type Mockusecase struct {
	ctrl     *gomock.Controller
	recorder *MockusecaseMockRecorder
	isgomock struct{}
}

// MockusecaseMockRecorder is the mock recorder for Mockusecase.
type MockusecaseMockRecorder struct {
	mock *Mockusecase
}

// NewMockusecase creates a new mock instance.
func NewMockusecase(ctrl *gomock.Controller) *Mockusecase {
	mock := &Mockusecase{ctrl: ctrl}
	mock.recorder = &MockusecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusecase) EXPECT() *MockusecaseMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *Mockusecase) Do(ctx context.Context, req *dto.Request) (*dto.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, req)
	ret0, _ := ret[0].(*dto.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockusecaseMockRecorder) Do(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*Mockusecase)(nil).Do), ctx, req)
}
