// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/resend_email_verification/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/resend_email_verification/usecase.go -destination=internal/app/usecases/resend_email_verification/usecase_mock_test.go -package=resend_email_verification
//

// Package resend_email_verification is a generated GoMock package.
package resend_email_verification

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockemailVerificationRepository is a mock of emailVerificationRepository interface.
type MockemailVerificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockemailVerificationRepositoryMockRecorder
	isgomock struct{}
}

// MockemailVerificationRepositoryMockRecorder is the mock recorder for MockemailVerificationRepository.
type MockemailVerificationRepositoryMockRecorder struct {
	mock *MockemailVerificationRepository
}

// NewMockemailVerificationRepository creates a new mock instance.
func NewMockemailVerificationRepository(ctrl *gomock.Controller) *MockemailVerificationRepository {
	mock := &MockemailVerificationRepository{ctrl: ctrl}
	mock.recorder = &MockemailVerificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemailVerificationRepository) EXPECT() *MockemailVerificationRepositoryMockRecorder {
	return m.recorder
}

// CreateForEmail mocks base method.
func (m *MockemailVerificationRepository) CreateForEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForEmail indicates an expected call of CreateForEmail.
func (mr *MockemailVerificationRepositoryMockRecorder) CreateForEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForEmail", reflect.TypeOf((*MockemailVerificationRepository)(nil).CreateForEmail), ctx, email)
}

// HasUnsentByEmail mocks base method.
func (m *MockemailVerificationRepository) HasUnsentByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUnsentByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUnsentByEmail indicates an expected call of HasUnsentByEmail.
func (mr *MockemailVerificationRepositoryMockRecorder) HasUnsentByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUnsentByEmail", reflect.TypeOf((*MockemailVerificationRepository)(nil).HasUnsentByEmail), ctx, email)
}
