// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=usecase_mock_test.go -package=register
//

// Package register is a generated GoMock package.
package register

import (
	context "context"
	reflect "reflect"

	user "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/user"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockuserRepository) Store(ctx context.Context, usr *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, usr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockuserRepositoryMockRecorder) Store(ctx, usr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockuserRepository)(nil).Store), ctx, usr)
}

// MockhashService is a mock of hashService interface.
type MockhashService struct {
	ctrl     *gomock.Controller
	recorder *MockhashServiceMockRecorder
	isgomock struct{}
}

// MockhashServiceMockRecorder is the mock recorder for MockhashService.
type MockhashServiceMockRecorder struct {
	mock *MockhashService
}

// NewMockhashService creates a new mock instance.
func NewMockhashService(ctrl *gomock.Controller) *MockhashService {
	mock := &MockhashService{ctrl: ctrl}
	mock.recorder = &MockhashServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhashService) EXPECT() *MockhashServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockhashService) Generate(s string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockhashServiceMockRecorder) Generate(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockhashService)(nil).Generate), s)
}
