// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=jwt
//

// Package jwt is a generated GoMock package.
package jwt

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MocktimeService is a mock of timeService interface.
type MocktimeService struct {
	ctrl     *gomock.Controller
	recorder *MocktimeServiceMockRecorder
	isgomock struct{}
}

// MocktimeServiceMockRecorder is the mock recorder for MocktimeService.
type MocktimeServiceMockRecorder struct {
	mock *MocktimeService
}

// NewMocktimeService creates a new mock instance.
func NewMocktimeService(ctrl *gomock.Controller) *MocktimeService {
	mock := &MocktimeService{ctrl: ctrl}
	mock.recorder = &MocktimeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeService) EXPECT() *MocktimeServiceMockRecorder {
	return m.recorder
}

// GetCurrentTime mocks base method.
func (m *MocktimeService) GetCurrentTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetCurrentTime indicates an expected call of GetCurrentTime.
func (mr *MocktimeServiceMockRecorder) GetCurrentTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentTime", reflect.TypeOf((*MocktimeService)(nil).GetCurrentTime))
}
