// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/usecases/login/contract.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/usecases/login/contract.go -destination=internal/app/usecases/login/usecase_mock_test.go -package=login
//

// Package login is a generated GoMock package.
package login

import (
	context "context"
	reflect "reflect"
	time "time"

	jwt "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/jwt"
	session "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/session"
	user "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/user"
	gomock "go.uber.org/mock/gomock"
)

// MockjwtService is a mock of jwtService interface.
type MockjwtService struct {
	ctrl     *gomock.Controller
	recorder *MockjwtServiceMockRecorder
	isgomock struct{}
}

// MockjwtServiceMockRecorder is the mock recorder for MockjwtService.
type MockjwtServiceMockRecorder struct {
	mock *MockjwtService
}

// NewMockjwtService creates a new mock instance.
func NewMockjwtService(ctrl *gomock.Controller) *MockjwtService {
	mock := &MockjwtService{ctrl: ctrl}
	mock.recorder = &MockjwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtService) EXPECT() *MockjwtServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockjwtService) Generate(secret []byte, claims *jwt.Claims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", secret, claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockjwtServiceMockRecorder) Generate(secret, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockjwtService)(nil).Generate), secret, claims)
}

// MockkeyedHashService is a mock of keyedHashService interface.
type MockkeyedHashService struct {
	ctrl     *gomock.Controller
	recorder *MockkeyedHashServiceMockRecorder
	isgomock struct{}
}

// MockkeyedHashServiceMockRecorder is the mock recorder for MockkeyedHashService.
type MockkeyedHashServiceMockRecorder struct {
	mock *MockkeyedHashService
}

// NewMockkeyedHashService creates a new mock instance.
func NewMockkeyedHashService(ctrl *gomock.Controller) *MockkeyedHashService {
	mock := &MockkeyedHashService{ctrl: ctrl}
	mock.recorder = &MockkeyedHashServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkeyedHashService) EXPECT() *MockkeyedHashServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockkeyedHashService) Generate(secret []byte, s string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", secret, s)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockkeyedHashServiceMockRecorder) Generate(secret, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockkeyedHashService)(nil).Generate), secret, s)
}

// MockpasswordHashService is a mock of passwordHashService interface.
type MockpasswordHashService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHashServiceMockRecorder
	isgomock struct{}
}

// MockpasswordHashServiceMockRecorder is the mock recorder for MockpasswordHashService.
type MockpasswordHashServiceMockRecorder struct {
	mock *MockpasswordHashService
}

// NewMockpasswordHashService creates a new mock instance.
func NewMockpasswordHashService(ctrl *gomock.Controller) *MockpasswordHashService {
	mock := &MockpasswordHashService{ctrl: ctrl}
	mock.recorder = &MockpasswordHashServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHashService) EXPECT() *MockpasswordHashServiceMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpasswordHashService) Compare(s, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", s, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpasswordHashServiceMockRecorder) Compare(s, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpasswordHashService)(nil).Compare), s, hash)
}

// MocktimeService is a mock of timeService interface.
type MocktimeService struct {
	ctrl     *gomock.Controller
	recorder *MocktimeServiceMockRecorder
	isgomock struct{}
}

// MocktimeServiceMockRecorder is the mock recorder for MocktimeService.
type MocktimeServiceMockRecorder struct {
	mock *MocktimeService
}

// NewMocktimeService creates a new mock instance.
func NewMocktimeService(ctrl *gomock.Controller) *MocktimeService {
	mock := &MocktimeService{ctrl: ctrl}
	mock.recorder = &MocktimeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeService) EXPECT() *MocktimeServiceMockRecorder {
	return m.recorder
}

// GetCurrentTime mocks base method.
func (m *MocktimeService) GetCurrentTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetCurrentTime indicates an expected call of GetCurrentTime.
func (mr *MocktimeServiceMockRecorder) GetCurrentTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentTime", reflect.TypeOf((*MocktimeService)(nil).GetCurrentTime))
}

// MockuuidService is a mock of uuidService interface.
type MockuuidService struct {
	ctrl     *gomock.Controller
	recorder *MockuuidServiceMockRecorder
	isgomock struct{}
}

// MockuuidServiceMockRecorder is the mock recorder for MockuuidService.
type MockuuidServiceMockRecorder struct {
	mock *MockuuidService
}

// NewMockuuidService creates a new mock instance.
func NewMockuuidService(ctrl *gomock.Controller) *MockuuidService {
	mock := &MockuuidService{ctrl: ctrl}
	mock.recorder = &MockuuidServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuuidService) EXPECT() *MockuuidServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockuuidService) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockuuidServiceMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockuuidService)(nil).Generate))
}

// MocksessionRepository is a mock of sessionRepository interface.
type MocksessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MocksessionRepositoryMockRecorder
	isgomock struct{}
}

// MocksessionRepositoryMockRecorder is the mock recorder for MocksessionRepository.
type MocksessionRepositoryMockRecorder struct {
	mock *MocksessionRepository
}

// NewMocksessionRepository creates a new mock instance.
func NewMocksessionRepository(ctrl *gomock.Controller) *MocksessionRepository {
	mock := &MocksessionRepository{ctrl: ctrl}
	mock.recorder = &MocksessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionRepository) EXPECT() *MocksessionRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MocksessionRepository) Save(ctx context.Context, ses *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, ses)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MocksessionRepositoryMockRecorder) Save(ctx, ses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MocksessionRepository)(nil).Save), ctx, ses)
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// FindByEmail mocks base method.
func (m *MockuserRepository) FindByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockuserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockuserRepository)(nil).FindByEmail), ctx, email)
}
