// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=usecase_mock_test.go -package=send_email_verification
//

// Package send_email_verification is a generated GoMock package.
package send_email_verification

import (
	context "context"
	reflect "reflect"

	user "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/user"
	event "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/event"
	gomock "go.uber.org/mock/gomock"
)

// MockverificationRepository is a mock of verificationRepository interface.
type MockverificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockverificationRepositoryMockRecorder
	isgomock struct{}
}

// MockverificationRepositoryMockRecorder is the mock recorder for MockverificationRepository.
type MockverificationRepositoryMockRecorder struct {
	mock *MockverificationRepository
}

// NewMockverificationRepository creates a new mock instance.
func NewMockverificationRepository(ctrl *gomock.Controller) *MockverificationRepository {
	mock := &MockverificationRepository{ctrl: ctrl}
	mock.recorder = &MockverificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockverificationRepository) EXPECT() *MockverificationRepositoryMockRecorder {
	return m.recorder
}

// GetUnsent mocks base method.
func (m *MockverificationRepository) GetUnsent(ctx context.Context, batchSize int) ([]*user.EmailVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnsent", ctx, batchSize)
	ret0, _ := ret[0].([]*user.EmailVerification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnsent indicates an expected call of GetUnsent.
func (mr *MockverificationRepositoryMockRecorder) GetUnsent(ctx, batchSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnsent", reflect.TypeOf((*MockverificationRepository)(nil).GetUnsent), ctx, batchSize)
}

// MarkAsSent mocks base method.
func (m *MockverificationRepository) MarkAsSent(ctx context.Context, tokens []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsSent", ctx, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsSent indicates an expected call of MarkAsSent.
func (mr *MockverificationRepositoryMockRecorder) MarkAsSent(ctx, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsSent", reflect.TypeOf((*MockverificationRepository)(nil).MarkAsSent), ctx, tokens)
}

// MockemailSendProducer is a mock of emailSendProducer interface.
type MockemailSendProducer struct {
	ctrl     *gomock.Controller
	recorder *MockemailSendProducerMockRecorder
	isgomock struct{}
}

// MockemailSendProducerMockRecorder is the mock recorder for MockemailSendProducer.
type MockemailSendProducerMockRecorder struct {
	mock *MockemailSendProducer
}

// NewMockemailSendProducer creates a new mock instance.
func NewMockemailSendProducer(ctrl *gomock.Controller) *MockemailSendProducer {
	mock := &MockemailSendProducer{ctrl: ctrl}
	mock.recorder = &MockemailSendProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemailSendProducer) EXPECT() *MockemailSendProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockemailSendProducer) Produce(ctx context.Context, ev event.EmailSend) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockemailSendProducerMockRecorder) Produce(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockemailSendProducer)(nil).Produce), ctx, ev)
}
