// Code generated by MockGen. DO NOT EDIT.
// Source: authorizer.go
//
// Generated by this command:
//
//	mockgen -source=authorizer.go -destination=authorizer_mock_test.go -package=authorizer
//

// Package authorizer is a generated GoMock package.
package authorizer

import (
	reflect "reflect"

	jwt "github.com/art-es/b2b-usage-based-billing-platform/services/service-auth/internal/app/domains/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockjwtService is a mock of jwtService interface.
type MockjwtService struct {
	ctrl     *gomock.Controller
	recorder *MockjwtServiceMockRecorder
	isgomock struct{}
}

// MockjwtServiceMockRecorder is the mock recorder for MockjwtService.
type MockjwtServiceMockRecorder struct {
	mock *MockjwtService
}

// NewMockjwtService creates a new mock instance.
func NewMockjwtService(ctrl *gomock.Controller) *MockjwtService {
	mock := &MockjwtService{ctrl: ctrl}
	mock.recorder = &MockjwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjwtService) EXPECT() *MockjwtServiceMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockjwtService) Parse(secret []byte, token string) (*jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", secret, token)
	ret0, _ := ret[0].(*jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockjwtServiceMockRecorder) Parse(secret, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockjwtService)(nil).Parse), secret, token)
}
