syntax = "proto3";

package orgn_service;
option go_package = "internal/generated/grpc/orgn_service";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service OrgnService {
    rpc Get (GetRequest) returns (GetResponse) {}
    rpc GetById (GetByIdRequest) returns (Orgn) {}
    rpc Create (CreateRequest) returns (CreateResponse) {}
    rpc Update (UpdateRequest) returns (google.protobuf.Empty) {}
}

message GetRequest {
    string user_id = 1;
    optional string cursor = 2;
}

message GetResponse {
    repeated Orgn orgns = 1;
    optional string next_cursor = 2;
}

message GetByIdRequest {
    string user_id = 1;
    string orgn_id = 2;
}

message Orgn {
    string id = 1;
    string name = 2;
    string user_id = 3;
    google.protobuf.Timestamp created_at = 4;
}

message CreateRequest {
    string user_id = 1;
    string name = 2;
}

message CreateResponse {
    string orgn_id = 1;
}

message UpdateRequest {
    string user_id = 1;
    string orgn_id = 2;
    optional string name = 3;
}
