syntax = "proto3";

package orgn_service;

option go_package = "internal/generated/grpc/orgn_service";

service OrgnService {
    rpc Get (GetRequest) returns (GetResponse) {}
    rpc GetById (GetByIdRequest) returns (Orgn) {}
    rpc Create (CreateRequest) returns (CreateResponse) {}
}

message GetRequest {
    string user_id = 1;
    optional string cursor = 2;
}

message GetResponse {
    repeated Orgn orgns = 1;
    optional string next_cursor = 2;
}

message GetByIdRequest {
    string id = 1;
}

message Orgn {
    string id = 1;
    string name = 2;
    string user_id = 3;
    // TODO: add created_at 
}

message CreateRequest {
    string user_id = 1;
    string name = 2;
}

message CreateResponse {
    string orgn_id = 1;
}
